## Ensemble algoritmaları :

Ensemble method için Bagging algoritmalardan Random forestı gördük. 

aynı veri seti üzerinde farklı modellerin eğitimini sağlar. Her model kendi tahminini yapar ve tahminlerin birleşiminden bir meta model oluşturulur. böylece en başarılı tahmini yapan güçlü bir model oluşturulur.
İkiye ayrılır : bagging ve boosting olarak. 

#### Bagging ve boosting algoritm benzerlikleri : 

oylama üzerine çalışır, aynı türdeki modelleri birleştirir. yani sadece 1 model kullanırlar. Baggingde tüm modeller ayrı ayrı oluşur. her birisi ayrı ağaç oluşturuyor. onların oylarına istinaden bir karar alınır. Random forestta ise buna ek olarak featureslerin de oyları alınır. yani onların ağırlığına bakılır. 

#### Bagging ve boosting farkları : 

bagging te her bir data modele ayrı ayrı girer, yani her bir ağaça tüm data girer ve hepsinin skorları alınır en iyi skor alınan ağacın modeli kabul edilir. Boostingte her ağacın oyu eşit. bagging algoritmasının içine decision tree gömülü halde bulunur. 

Boostingte ise data ilk ağaca girer, sonrasında diğer ağaçlara yapraktan alınan sonuca göre girer, yani her yaprak birbirini etkiler. burda ise en iyi skor elde edenin oyu daha fazla olacaktır. 

bagging algoritmaları varyansı düşürmek için, boosting algoritmaları ise bias değerini düşürmek için hareket eder. sebebi ise bagging algoritmaları birbirlerinden habersiz çalışırlar yani tüm data her bir ağaca monte edilerek çalışır, boosting algoritmalarında ise her ağacın skoru diğer ağacı etkileyecektir. 

#### Bagging çalışma prensibi şu şekilde : örneğin bir muharlık seçimi var 100 kişi oy kullandı. hepsi birbirinin ne oy verdiğinde habersiz, ve oylama sonunda sandık sayılıyor, sonucunda 100 oydan en fazla oy alan muhtar oluyor. yani datayı her seferinde her ağaç datanın farklı yönlerine bakarak skorlar ve en yüksek skor alan seçilir.

#### Boosting te ise : yine 100 kişi oy kullanıyor, ama bu sefer her oy kullanan birbirini etkiliyor, yani ilk oyu veren 2. oyu vereni, 2. oyu veren 3. oyu vereni etkiliyor.  yani ilk ağacın baktığı yere 2. ağaç bakmıyor o farklı bir yere bakıyor ve sonrasında tüm veriler toplanır, ortalama değer alınır.  er ağaç bilgisini diğer ağaca aktarır, bagginde ise aktarım olmaz.

### Boosting :

Tüm datasetini alır, modele atar, bu model bir prediction yapar, predictiona göre yeniden yapılan hatalara göre data noktalarını ağırlıklandırır, sonra sıradaki modele gider ama bir önceki datadan elde ettiği bilgileri aktararak prediction yapar, sırasıyla tüm data bitinceye kadar bu süreç devam eder. sonra sırasıyla her modelin oyunu alır, en yüksek olan oya göre predict yapar. yani kısacası bir data seçer sonra ondan elde ettikleri ile sırasıyla tüm modellere bilgileri aktararak devam eder. en sonda en yüksek ağırlık değeri alanı seçer. Boosting algoritmada her bir ağaca stump denir.

2 tane algoritması vardır. AdaBoost ve Gradient Boosting tir. En önemli hyper parametreleri base_estimator ve n_estimator dur.

#### AdaBoost :

Datayı seçiyor ve onu en iyi böleceği yeri bulup ordan bölüyor. sonra tahminleme yapıyor. yapılan hatalı tahminne göre bir sonra ki ağacı farklı bir noktadan bölüyor. sonra o ağaçta yaptığı hatalı tahminlere göre yine diğer ağacı farklı yerden ayırıyor. her hata değeri sonucu bir ağırlık katsayısı hesaplanır. hata ne kadar az ise ağırlık değeri o kadar fazla olur. ve en fazla ağırlık değeri olan seçilir. log2 tabanına göre ağırlıkları hesaplanır. yalış tahmin edilen yerler ağırlıklandırılarak çalışır.

##### a . base_estimator parameteresi : Default bırakırsak max_depth değeri 1 olan, bir decision tree oluşturur. eğer logistic regression verirsek ise logistic regresyon oluşturur.

##### b. n_estimators : default değeri 50 dir. kaç tane oluşturacağımız ağaç adedi.

#### Gradient Boosting :

Bir önceki modelin yaptığı hataları iyileştirme üzerine çalışıyor. elimizde X futureler ve y targetımız var. ilk modele sokuyor. y - y_pred = residual değerlerini buluyor. sonra 2. modele geçerken artık futreler ile diğer residualleri tahmin etmeye çalışıyor. yani ilk model residual değerinden 2. model resudial değerlerini çıkarıyor. ve sırasıyla tüm model bitinceue kadar bu yöntem ile ilerliyor. learning_rate değeri sayısı kadar resudial değerlerini çıkarır. learning_rate = 0 olsun diyelim. resudial değeri 0 oluncaya kadar devam eder ama overfit durumu olabilir.

#### XGBoost (Extreme Gradient Boosting) :

En kullanışlı boosting algoritması. kendi içinde bir alfa değeri gibi regulazisyon değeri uygulayabiliriz. missing value de bile çalışabilir. ama missing valueden mutlaka kurtulmak gerekir. her bir ağaca geçerken kendi içinde cross validate yapar. aynı zamanda tüm işlemcileri kullanabilmekteyiz. Büyük datalarda hızlıdır. Eda ya gerek kalmadan missing valueleri ekarte eder. feature importance(futurelerden hangisi daha önemli onu veriyor.) Görselleştirme yapılamaz. açıklaması çok zor. hyper parametresi oldukça fazla.

##### a . n_estimator parametresi default olarak 100 tane belirlenmiş.

##### b. subsample parametresi default olarak 1 belirlenmiş. 1 demek tüm veriyi kullan demektir. bölmeden kullan demek.

##### c. max_depth : default değeri 3 tür.

##### d. learning_rate : default değeri 0.1 dir. n_estimator ile learning_rate dengelenmelidir.



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams["figure.figsize"] = (10,6)
import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")

In [2]:
df = pd.read_csv('advertising2.csv')
df.head()
# internet sitesi tıklama durumları. sırasıyla tıklama durumlarını etkileyen futureler var.

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad Topic Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0  
3  2016-01-10 02:31:19              0  
4  2016-06-03 03:36:18              0

### Exploratory Data Analysis and Visualization :

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64  
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object 
 5   City                      1000 non-null   object 
 6   Male                      1000 non-null   int64  
 7   Country                   1000 non-null   object 
 8   Timestamp                 1000 non-null   object 
 9   Clicked on Ad             1000 non-null   int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 78.2+ KB


In [4]:
df.describe()

Daily Time Spent on Site          Age   Area Income  \
count               1000.000000  1000.000000   1000.000000   
mean                  65.000200    36.009000  55000.000080   
std                   15.853615     8.785562  13414.634022   
min                   32.600000    19.000000  13996.500000   
25%                   51.360000    29.000000  47031.802500   
50%                   68.215000    35.000000  57012.300000   
75%                   78.547500    42.000000  65470.635000   
max                   91.430000    61.000000  79484.800000   

       Daily Internet Usage         Male  Clicked on Ad  
count           1000.000000  1000.000000     1000.00000  
mean             180.000100     0.481000        0.50000  
std               43.902339     0.499889        0.50025  
min              104.780000     0.000000        0.00000  
25%              138.830000     0.000000        0.00000  
50%              183.130000     0.000000        0.50000  
75%              218.792500     1.000000        1.00000  
max              269.960000     1.000000        1.00000

### Train | Test Split

In [6]:
from sklearn.model_selection import train_test_split

X = df[['Daily Time Spent on Site', 'Age', 'Area Income','Daily Internet Usage', 'Male']]
y = df['Clicked on Ad']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

### Modelling and Model Performance : 

Adaboost modelini kullanacağız. ensemble methodlardan 

In [7]:
from sklearn.ensemble import AdaBoostClassifier
# target categoric olduğu için Classifier dedik.

#### Default Model : 

In [16]:
ada_model = AdaBoostClassifier(random_state=42)
ada_model.fit(X_train, y_train)
y_pred = ada_model.predict(X_test)

# randomforestta her ağaç birbirinden bağımsızdı, her ağacın verdiği oy birbirine eşitti. en son sayıyorduk. en fazla çıkan oy
# hangi classa aitse o classı atıyorduk. 

# adaboostingte ise ağaçlar birbirini etkiler. 

#### Metrics : 

In [17]:
from sklearn.metrics import recall_score, f1_score, accuracy_score, precision_score, confusion_matrix, classification_report
from sklearn.metrics import roc_auc_score, plot_confusion_matrix

def eval_metric(model, X_train, y_train, X_test, y_test):
    y_train_pred = model.predict(X_train)
    y_pred = model.predict(X_test)
    print("Test_Set")
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print()
    print("Train_Set")
    print(confusion_matrix(y_train, y_train_pred))
    print(classification_report(y_train, y_train_pred))

In [18]:
eval_metric(ada_model, X_train, y_train, X_test, y_test)

Test_Set
[[41  3]
 [ 4 52]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92        44
           1       0.95      0.93      0.94        56

    accuracy                           0.93       100
   macro avg       0.93      0.93      0.93       100
weighted avg       0.93      0.93      0.93       100


Train_Set
[[454   2]
 [ 12 432]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       456
           1       1.00      0.97      0.98       444

    accuracy                           0.98       900
   macro avg       0.98      0.98      0.98       900
weighted avg       0.98      0.98      0.98       900



### Cross Validate Control : 

In [19]:
from sklearn.model_selection import cross_validate

model = AdaBoostClassifier(random_state=42)

scores = cross_validate(model, X_train, y_train, scoring = ["accuracy", "precision", "recall", "f1"], cv = 10)
df_scores = pd.DataFrame(scores, index = range(1, 11))
df_scores.mean()[2:]

test_accuracy     0.960000
test_precision    0.968795
test_recall       0.950505
test_f1           0.958988
dtype: float64

### AdaBossting Çalışma mantığı : 

örneğin elimizde bir data olsun ve 1000 tane değeri olsun. her ağaca 1000 tane değer aktarılır. fakat bu 1000 tane değer her ağaca aynı şekilde aktarılmaz. diyelim ilk ağaca 1000 tane gözlemi soktu. ve bu ağaçta doğru tahmin ettiği ve yanlış tahmin ettiği değerler çıktı. 2. ağaca tekrardan 1000 gözlem sokarken hatalı tahmin edilen gözlemleri ağırlıklandırarak sokar. yani hatalı tahmin edilen gözlemlerin sayılarını arttırıp tekrardan diğer ağaca aktarir. her ağaçta hata sayısı azalır. learnin_rate ise bir sonraki ağaca hatalı gözlemleri aktarırken hataları ne kadar ağırlıklandıracağını belirler. eğer learning_rate sayısının artması hatayı 0 ra indirecektir. ve bu sebeple overfiting tehlikesi artacaktır. bizim için ideal olan ağaç sayımızın fazla, learnin_rate sayımızn az olmasıdır. ağaç sayımız n_estimator, hata ağırlık oranımız lerning_rate dir. 

In [20]:
ada_model.estimator_errors_

# ile hata sayılarına göre ağırlık katsayıları belirler. burdaki katsayıların sayısı n_estimator sayısı kadardır.

array([0.09666667, 0.15660636, 0.29526371, 0.28593614, 0.35590938,
       0.39210515, 0.36269642, 0.36981063, 0.38415067, 0.35773598,
       0.3516825 , 0.37454891, 0.42018968, 0.42873964, 0.39973475,
       0.43748548, 0.40219137, 0.45770547, 0.46274743, 0.40702713,
       0.42891649, 0.43044307, 0.36904407, 0.42357491, 0.44299881,
       0.38996104, 0.40345756, 0.41149436, 0.43690794, 0.42621951,
       0.47745572, 0.47172434, 0.46458273, 0.42113437, 0.44541302,
       0.4184376 , 0.42957773, 0.4504647 , 0.45939104, 0.42479237,
       0.42440331, 0.42555073, 0.48041565, 0.46741902, 0.43362918,
       0.427282  , 0.39972274, 0.41673326, 0.45575418, 0.44847986])

In [21]:
# ağaç sayımız 3 tane olsun : 

model = AdaBoostClassifier(n_estimators=3, random_state=42)
model.fit(X_train,y_train)

AdaBoostClassifier(n_estimators=3, random_state=42)

In [22]:
model.estimator_errors_
# her ağacın errorlarını döndürür. değer 0 ra ne kadar yakınsa o kadar iyi tahmin yapmış demektir. 

array([0.09666667, 0.15660636, 0.29526371])

In [23]:
1/2*np.log((1-0.09666667)/0.09666667) # 1. ağaç için ağırlıklandırma katsayısı : class değeri 1

1.117411476360216

In [24]:
1/2*np.log((1-0.15660636)/0.15660636) # 2. ağaç için ağırlıklandırma katsayısı : class değeri 0

0.8418492023096668

In [25]:
1/2*np.log((1-0.29526371)/0.29526371) # 3. ağaç için ağırlıklandırma katsayısı : class değeri 0

0.43497739343711583

In [27]:
# 3 ağaç içinden 1 class değerine sahip ağacın ağırlıklandırma katsayısı 1.17, 0 class değerine sahip ağaçların ağırlıklandırma
# katsayıları toplamı : 0.84 + 0.43 = 1.27 dir. 0 classına sahip ağaçların katsayıları 1 classına sahip ağaçtan daha büyük 
# olduğu için class değeri 0 olacaktır.

In [28]:
n_estimator = np.array([20,30,50,100,200,250,300,350,400])
learning_rate = np.linspace(0.01,5,50)

### Gridsearch

In [29]:
from sklearn.model_selection import GridSearchCV

model = AdaBoostClassifier(random_state= 42)

param_grid = {"n_estimators": n_estimator, "learning_rate": learning_rate}

ada_grid_model = GridSearchCV(model, param_grid, cv=5, scoring= 'f1')

ada_grid_model.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=AdaBoostClassifier(random_state=42),
             param_grid={'learning_rate': array([0.01      , 0.11183673, 0.21367347, 0.3155102 , 0.41734694,
       0.51918367, 0.62102041, 0.72285714, 0.82469388, 0.92653061,
       1.02836735, 1.13020408, 1.23204082, 1.33387755, 1.43571429,
       1.53755102, 1.63938776, 1.74122449, 1.84306122, 1.94489796,
       2.04673469, 2.14857143, 2.25040816, 2.352..., 2.45408163,
       2.55591837, 2.6577551 , 2.75959184, 2.86142857, 2.96326531,
       3.06510204, 3.16693878, 3.26877551, 3.37061224, 3.47244898,
       3.57428571, 3.67612245, 3.77795918, 3.87979592, 3.98163265,
       4.08346939, 4.18530612, 4.28714286, 4.38897959, 4.49081633,
       4.59265306, 4.6944898 , 4.79632653, 4.89816327, 5.        ]),
                         'n_estimators': array([ 20,  30,  50, 100, 200, 250, 300, 350, 400])},
             scoring='f1')

In [30]:
ada_grid_model.best_params_

{'learning_rate': 0.11183673469387755, 'n_estimators': 100}

In [32]:
eval_metric(ada_grid_model, X_train, y_train, X_test, y_test)

Test_Set
[[40  4]
 [ 3 53]]
              precision    recall  f1-score   support

           0       0.93      0.91      0.92        44
           1       0.93      0.95      0.94        56

    accuracy                           0.93       100
   macro avg       0.93      0.93      0.93       100
weighted avg       0.93      0.93      0.93       100


Train_Set
[[453   3]
 [ 19 425]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.98       456
           1       0.99      0.96      0.97       444

    accuracy                           0.98       900
   macro avg       0.98      0.98      0.98       900
weighted avg       0.98      0.98      0.98       900



In [33]:
eval_metric(ada_model, X_train, y_train, X_test, y_test)

Test_Set
[[41  3]
 [ 4 52]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92        44
           1       0.95      0.93      0.94        56

    accuracy                           0.93       100
   macro avg       0.93      0.93      0.93       100
weighted avg       0.93      0.93      0.93       100


Train_Set
[[454   2]
 [ 12 432]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       456
           1       1.00      0.97      0.98       444

    accuracy                           0.98       900
   macro avg       0.98      0.98      0.98       900
weighted avg       0.98      0.98      0.98       900

